### ISSUE TITLE
Save wont load with latest version (0.2.3)

### ISSUE THREAD

**Issue by Darkvoid090** [NotoriousPyro/CoI.Mod.Better#3]
Mods used in the save are CoI.Mod.Better and captain of cheats [https://github.com/altmank/CaptainOfCheats/releases/tag/v1.9.0](url) (I used the latest versions for both)
The save and logs are here because they exceed the 25mb limit for github:
[https://drive.google.com/file/d/1kM3uDVfLB3UUzjhzgV5MHlG5YowgjMMu/view?usp=sharing](url)
The save wont load, something in the log file about void producer loose cheat.

**Comment by NotoriousPyro** [comment]
You have cheats disabled? It may be that you need to restart from an earlier save, one before you used any of the forked versions... What versions did you use from here?

**Comment by NotoriousPyro** [comment]
Also it's possible your 'cheats' settings may need adjusting, those void producers are only supposed to exist if the cheats are enabled...
